# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ellomix' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ellomix
  pod 'DCKit', :git => 'https://github.com/andrew8712/DCKit.git'
  pod 'AFNetworking'

  target 'EllomixUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
